package com.dailywallet.model.enums;

public enum TransactionType {
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    ALLOCATION,
    REALLOCATION,
    INTEREST_CREDIT,
    SCHEDULED_RELEASE,
    MPESA_DEPOSIT,
    MPESA_WITHDRAWAL,
    MMF_INVESTMENT,
    MMF_REDEMPTION,
    OVERDRAFT_USE,
    OVERDRAFT_REPAYMENT,
    OVERDRAFT_INTEREST
}
