spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.dailywallet: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

app:
  mpesa:
    api-url: https://api.safaricom.co.ke
